<?php

class Cliente extends Usuario
{


    public function __construct()
    {
    }

    public function Pagar(){


    }

    public function Registro()
    {
        parent::Registro(); // TODO: Change the autogenerated stub
    }

    public function DarBajaUsuario(){



    }


}